### ISSUE TITLE
Text wrap

### ISSUE THREAD

**Issue by giving-sesame** [Fox2Code/FoxMagiskModuleManager#10]
Hi, I have a suggestion for improvement. Please make text wrap on the screen with module installation log.

**Comment by Fox2Code** [comment]
I might add a setting in a future version to use text wrapping, but I will still keep side scrolling as a default behavior.

**Comment by giving-sesame** [comment]
Extra setting is okay for this. Thank you

**Comment by Fox2Code** [comment]
WIP, high chances to be implemented in `0.3.0`!
(There will be a `0.2.7` before a `0.3.0` tho)

**Comment by giving-sesame** [comment]
Thanks a lot!
