### ISSUE TITLE
[BUG] ROOT FATAL ERROR

### ISSUE THREAD

**Issue by UnrealKaraulov** [Fox2Code/FoxMagiskModuleManager#101]
**Describe the bug**

**To Reproduce**
1. Go to 'FoxMagiskModuleManager'
2. Click on 'nothing'
3. Scroll down to 'nothing'

**Expected behavior**
Root Detected
**Screenshots**
![Screenshot_20220310-124111](https://user-images.githubusercontent.com/88730285/157634944-bc03c6d0-cf26-4048-989f-a1824ed4cbca.png)
![Screenshot_20220310-124055](https://user-images.githubusercontent.com/88730285/157634970-5c935b99-dec8-45e3-be22-4e43f52f2ce8.png)
![Screenshot_20220310-124033](https://user-images.githubusercontent.com/88730285/157634989-e6c3fc26-72c1-42e1-a8d3-031a19febcb9.png)

**Device info(please complete the following information):**
 - Device: [e.g. Nokia 3.1]
 - OS: [ROM and version, Stock and Android 10]
 - App Version [e.g. 0.4.0-rc1.apk]

**Additional context**
Nothing

**Comment by UnrealKaraulov** [comment]
@Fox2Code possible regression. Old version works without problems.

**Comment by Fox2Code** [comment]
Android fragmentation is always a fun thing, a similar issues has already been reported, I'm currently unable to work on Fox Mmm for a bit, it will be fixed in RC-2

**Comment by UnrealKaraulov** [comment]
Thanks! waiting for RC2...

**Comment by Fox2Code** [comment]
Test if [`0.4.0-rc2`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/0.4.0-rc2) fixed the issue please.

If it doesn't work use debug build and give a `logcat` of the error.

**Comment by UnrealKaraulov** [comment]
@Fox2Code yes this is works!
