### ISSUE TITLE
Download only mode 

### ISSUE THREAD

**Issue by Raif1** [Fox2Code/FoxMagiskModuleManager#106]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want a download only mode. There ill be able to download modules and not getting it auto installed.i want to manually install them. This mode will not have the su permisson. And i think this feature may help the app getting released on the fdroid repo.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by VladWinner** [comment]
> And i think this feature may help the app getting released on the fdroid repo.

But F-Droid allows devs to add apps that require root.
Just add it to "Build Metadata":
RequiresRoot: 'yes'

**Comment by Raif1** [comment]
Oo i didnt know weelll but i would also like a download only mode

**Comment by Fox2Code** [comment]
"Download only mode" you mean "Lockdown mode"?
This mean I already implemented that feature.

Also my app can download modules even without root.
I checked and Androidacy page was supposed to show a button for that but doesn't for some reason.
Well I will label this as a bug as the feature is supposed to be already in the app.

Also F-Droid repo release is not priority for now, I will see later to do an F-Droid version of the app.

**Comment by Fox2Code** [comment]
[`0.4.0-rc3`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/0.4.0-rc3) should have fixed the ability to download Androidacy modules.

Please close if fixed.

**Comment by Raif1** [comment]
Can you please rename lockdown mode to download mode?

**Comment by Raif1** [comment]
> [`0.4.0-rc3`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/0.4.0-rc3) should have fixed the ability to download Androidacy modules.
> 
> Please close if fixed.

Install option seems to be this ..


![dgdgdg.png](https://user-images.githubusercontent.com/93464125/160240442-93926c34-cb62-42aa-975f-3f7ad11d61ec.png)

And i mean where is it saving files without the storage permission?

**Comment by Fox2Code** [comment]
> Can you please rename lockdown mode to download mode?

No, too many translation have been already done.

Also this error is an Androidacy back-end issue, my contact with Androidacy told me there was recently a problem with the API that caused some downtime today, please test again later to see if there is any improvement.

From the test I done while the API was working everything is fine.

Also do download modules without requesting storage API it just open the download URL in the Web Browser, this is a trick to ask as few permissions as possible. (Well since my app needs root it's a bit pointless, I know)

**Comment by Raif1** [comment]
> > Can you please rename lockdown mode to download mode?
> 
> No, too many translation have been already done.
> 
> Also this error is an Androidacy back-end issue, my contact with Androidacy told me there was recently a problem with the API that caused some downtime today, please test again later to see if there is any improvement.
> 
> From the test I done while the API was working everything is fine.
> 
> Also do download modules without requesting storage API it just open the download URL in the Web Browser, this is a trick to ask as few permissions as possible. (Well since my app needs root it's a bit pointless, I know)

Can we use saf here bcs i want my modules organized?
