### ISSUE TITLE
[BUG] English only mode not working

### ISSUE THREAD

**Issue by UnrealKaraulov** [Fox2Code/FoxMagiskModuleManager#109]
**Describe the bug**
 English only mode not working

**To Reproduce**
1. Go to Settings
2. Scroll down to "Интерфейс всегда на английском языке"
3. Click on this
5. See russian interface....

**Expected behavior**
English only mode!

**Screenshots**

**Device info(please complete the following information):**
 - Device: Nokia 3.1
 - OS: Android 8.1
 - App Version 0.4.0

**Additional context**

**Comment by Fox2Code** [comment]
I know, this is why it's hidden behind dev mode, I spend too many hours trying to fix that.
You didn't checked closed issues.
There is the original issue: #71
