### ISSUE TITLE
Invisible module

### ISSUE THREAD

**Issue by giving-sesame** [Fox2Code/FoxMagiskModuleManager#11]
Please note, that Module Manager does not see the module which was created by 3C All-in-one Toolbox (https://play.google.com/store/apps/details?id=ccc71.at.free). This module is located in /data/adb/modules and in the attachment you can find the archive with relevant folder.

[3c.zip](https://github.com/Fox2Code/FoxMagiskModuleManager/files/7768931/3c.zip)

**Comment by Fox2Code** [comment]
I might have an idea what this is happening, I will fix it in next bug-fix release.

**Comment by Fox2Code** [comment]
Latest release should have fixed this bug.

**Comment by giving-sesame** [comment]
Thank you, it is fixed. Could you please tell me what's wrong with this module.prop? I will write to 3c author and ask to correct it.

**Comment by Fox2Code** [comment]
Probably module id miss-match with folder name.
The module id is supposed to match with module folder name, the folder name was `3c` but the id was `3c-android`.
