### ISSUE TITLE
Su requests in lockdown mode 

### ISSUE THREAD

**Issue by Raif1** [Fox2Code/FoxMagiskModuleManager#112]
**Is your feature request related to a problem? Please describe.**
Kinda annoying 

**Describe the solution you'd like**
Please stop asking su after setting the app in lockdown mode. And remove this when in lockdown mode 

 ![lk.png](https://user-images.githubusercontent.com/93464125/160984804-00ca33cf-4d3e-4a51-81fc-620060b71236.png)

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Fox2Code** [comment]
"Lockdown mode." is not to not ask for root, it's to prevent modification on modules.

Root is still needed to get module info and list, the app goal is also to check on modules.
