### ISSUE TITLE
Suggestion: change name to "MagiskModuleManager"

### ISSUE THREAD

**Issue by coxackie** [Fox2Code/FoxMagiskModuleManager#118]
First of all, many _many_ thanks for bringing to life this elegant app to solve the gap that was there after the latest Magisk changes. This is by now (and, I am sure, in the future) the _de facto_ manager for magisk modules. Therefore, I would suggest to consider changing the name to simply "MagiskModuleManager".

 Please note that I am saying this in no way to remove your "stamp" from the name - I just mean that it is not just "Fox's Magisk Module Manager" is _the_ Magisk Module Manager.

**Comment by Fox2Code** [comment]
Hi, please think about your proposal, you should be able to figure out by yourself why it's named like this.
You should also think from Magisk official creators perspective, and tell you what happen if I apply your suggestion.

You seems to have very good communication skill.
Also don't hesitate to open other suggestion on there, I'm 100% ok with peoples doing mistakes here.

You also seems open minded and to listen to peoples, so I know I'm not wasting my time talking to you.
Also don't let yourself be taken advantage of, or things might go very bad in your life.

You can join my telegram chat here if you wish: https://t.me/Fox2Code_Chat

**Comment by coxackie** [comment]
Apologies, I hope I did not offend you. Of course I understand why you named it like this, I just wanted to point out that since this is (and will be) the most popular magisk modules manager, it would merit a name that is beyond author. I totally respect whatever decision you make. For the record, i do not think anyone would object a name like the one I suggest - it was the magisk creator that decided to drop support for this feature, so there is no appropriation from your side.

 Anyway, keep up the awesome work!

**Comment by Fox2Code** [comment]
I would have not offered you to join my telegram chat if you offended me, also it's really obvious you are being under some kind of abuse or harassment, you talk in fear like if I was going to kill you.

What is happening in your life is not normal, you should not feel fear talking to me, please don't believe peoples that say "You are fine", I did and it caused me real life health issues.

Also disturbing profile pics can make peoples more aggressive, but I'm really more worried about your health.

If you join telegram group, the mods I picked were carefully picked, you should be safe there.
