### ISSUE TITLE
[BUG] wrong version number?

### ISSUE THREAD

**Issue by ZooNooU** [Fox2Code/FoxMagiskModuleManager#139]
**Describe the bug**
I downloaded the latest update and it says that it's 0.4.0 instead of 0.4.5

**To Reproduce**
1. Open the app
2. Still seeing the update promote
3. app version in android settings is 0.4.0

**Expected behavior**
The app should be updated to 0.4.5

**Screenshots**
![Screenshot_20220503-155534_Settings](https://user-images.githubusercontent.com/103965987/166478436-66ee5bfc-92da-45c3-81a0-d86de819fc91.png)

**Device info(please complete the following information):**
 - Device: OnePlus 5
 - OS: CrDroid 7.18
 - App Version: 0.4.5 (supposedly)

**Additional context**
I think the wrong version is uploaded to be downloaded (if that makes sense)

**Comment by ZooNooU** [comment]
nvm
it took time to show up 😅

**Comment by roirraWedorehT** [comment]
I was having the similar problem that I couldn't update from 0.4.4 to 0.4.5.  I had downloaded 0.4.5 multiple times.  It appears that the 0.4.5 apk has been newly updated, however, as it's just slightly larger.  Glad it wasn't just me.  :)
