### ISSUE TITLE
[BUG] failed to get acess to root

### ISSUE THREAD

**Issue by Felix-Kyun** [Fox2Code/FoxMagiskModuleManager#144]
I just installed the app and granted it root perms but when I open the app it's says `failed to get access to root or magisk`

![Screenshot_2022-05-07-13-21-36-938_com topjohnwu magisk](https://user-images.githubusercontent.com/99094581/167244801-f93a0be8-8a71-4366-ae41-8061430cf179.jpg)

 - Device: MI MAX 2
 - OS: miui 11, Android 7.1
 - App Version 0.4.5

I am using magisk 24.3 with zygisk enabled [ as some of my root apps r not working after enabling zygisk]

**Comment by Fox2Code** [comment]
Got report like this before, never got the info I needed to fix it, I may have fixed that in debug build for `0.5.0`, I just need to wait to be sure.

But I still don't have enough info.

**Comment by vielspam** [comment]
Just compiled and installed latest version fom source.
For me the Problem is gone.
Have had it on several phones since 0.4.3 i think...
Thanks

**Comment by Felix-Kyun** [comment]
Just changed my rom and it looks like the problem is fixed, maybe it was a problem with A7, anyways it works completely fine on a11
![Screenshot_20220512-192529_crDroid_Home](https://user-images.githubusercontent.com/99094581/168092200-5c56e8d4-379e-498f-b741-763bf77824f1.png)

**Comment by Felix-Kyun** [comment]
Just changed my rom and it looks like the problem is fixed, maybe it was a problem with A7, anyways it works completely fine on a11
![Screenshot_20220512-192529_crDroid_Home](https://user-images.githubusercontent.com/99094581/168092200-5c56e8d4-379e-498f-b741-763bf77824f1.png)

**Comment by Fox2Code** [comment]
Ok thx.

**Comment by NoUserNameForYou** [comment]
> Just compiled and installed latest version fom source. For me the Problem is gone. Have had it on several phones since 0.4.3 i think... Thanks

Can you share it?

**Comment by GalaxyNote10** [comment]
> > Just compiled and installed latest version fom source. For me the Problem is gone. Have had it on several phones since 0.4.3 i think... Thanks
> 
> Can you share it?

Would be better if a new Version will be released soon.
Otherwise you will get into troubble with the signed version.
@Fox2Code: 
  Do you plan to release a new version in the near future?
  You closed several bug since last release (from issue tracker).
