### ISSUE TITLE
[BUG] Magisk not detected on Android 7.1

### ISSUE THREAD

**Issue by leapofazzam123** [Fox2Code/FoxMagiskModuleManager#151]
**Describe the bug**
The app couldn't detect the superuser access granted by Magisk canary

**To Reproduce**
1. Have root enabled
2. Install the app
3. Open the app
4. Grant superuser access

**Expected behavior**
It should detect the superuser access

**Screenshots**
![Screenshot_20220521-095600](https://user-images.githubusercontent.com/76893443/169632610-f76fd7e3-b135-4344-93ae-8782f66129d0.png)

**Device info**
 - Device: Oppo Neo 5 (Model string: OPPO 1201)
 - OS: AOSP Extended 4.6 (Android 7.1.2)
 - App Version: 0.4.5

**Comment by Fox2Code** [comment]
Please send logcat, issue will be closed if not able to send a logcat with a debug build in a timely manner.

**Comment by leapofazzam123** [comment]
nvm i got it fixed

**Comment by Fox2Code** [comment]
How did you fixed it?

**Comment by TheGreySquare** [comment]
> How did you fixed it?

I was able reproduce that bug on Android 7.1.2 phone with Magisk 20.3 installed. Installing newer Magisk 21.0 fixed that issue for me.
