### ISSUE TITLE
[BUG] Can't install modules or show info

### ISSUE THREAD

**Issue by Xitee1** [Fox2Code/FoxMagiskModuleManager#153]
**Describe the bug**
I can no longer install modules or show the info.

**To Reproduce**
1. Update everything
2. Search for a module
3. Click the info or install button

**Expected behavior**
I can see the info page and can install the modules

**Screenshots**
![Screenshot_20220526-135548_Fox's Magisk Module Manager.png](https://user-images.githubusercontent.com/59659167/170483642-6ebc7462-8e2b-4305-b52f-3277367086ff.png)

**Device info(please complete the following information):**
 - Device: Samsung S9+
 - OS: Stock (rooted)
 - App Version 0.4.5

**Additional context**

**Comment by nift4** [comment]
It's an androidacy repo problem. Please report it to them.
