### ISSUE TITLE
[BUG] Some problem with language selector

### ISSUE THREAD

**Issue by ender-zhao** [Fox2Code/FoxMagiskModuleManager#163]
When I choose another language, I have to choose it twice or it can't switch. The language changed when the app background is closed cannot be saved and will revert to English the next time it is opened.

And, consider adding Chinese to language selector please. 😊

**Device info:**
- Device: Pixel 6 pro
- OS: Android 12
- System Language: English
- App Version: 0.5.0

**Comment by Fox2Code** [comment]
Chinese is already added to language selector, but due to a bug it didn't show up.

**Comment by Fox2Code** [comment]
Fixed! I spend more time battling against JitPack than fixing actual bugs tho.
https://github.com/Fox2Code/RosettaX <- It's fixed!

**Comment by ender-zhao** [comment]
Thanks!
