### ISSUE TITLE
[BUG] App crashing when clikcing install module for some(may be all) apps 

### ISSUE THREAD

**Issue by shaik7abdul7khallik** [Fox2Code/FoxMagiskModuleManager#175]
**Describe the bug**
the app is crashing when trying to install module

**To Reproduce**
1. open app
2. let the repos load
3. go to Mixplorer and download module
4. then on Mixplorer click install module.

**Expected behavior**
The app should install Mixplorer module.

**Device info(please complete the following information):**
 - OS: [ROM and version, ie Havoc-OS 4.12]
 - App Version [e.g. 22]

**Additional context**
 attached lo
[log.txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/9122703/log.txt)

**Comment by Fox2Code** [comment]
Thanks, I forgot to fix that, I will do an hotfix.

**Comment by Fox2Code** [comment]
Thanks for reporting the issue, crash has been fixed in `0.5.6`.
