### ISSUE TITLE
Periodic Notifications for TWRP A/B Retention Script

### ISSUE THREAD

**Issue by tim1aust** [Fox2Code/FoxMagiskModuleManager#187]
I'm getting frequent notifications "Found 1 module updates" with the lates update (0.6.0), but the only module that is updatable is the subject module. 

But that module is *always* updatable, by design. Not trying to be a pest and ask for an exception for that one module, but... it's kind of annoying.

Thanks,
--tim

**Comment by HuskyDG** [comment]
TWRP A/B Retention Script is not a normal module

**Comment by Fox2Code** [comment]
Hum... This should not happens.

**Comment by osm0sis** [comment]
😝😘
