### ISSUE TITLE
[BUG] Finicky text behavior when scrolling slow with blur on

### ISSUE THREAD

**Issue by HiFiiDev** [Fox2Code/FoxMagiskModuleManager#191]
**Describe the bug**
Weird text behavior when scrolling

**To Reproduce**
1. Ensure window blur is enabled
2. Scroll slowly

**Expected behavior**
It almost looks like the text is jumping up when scrolling earlier than it should. I feel like there should be no jitter when scrolling slowly, reading the descriptions

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://photos.app.goo.gl/ZU87hC96GNRYgymr8) <--- screen recording 

**Device info(please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Latest Android 13 beta
 - App Version 0.6.1 (https://github.com/Fox2Code/FoxMagiskModuleManager/actions/runs/2855430966)

**Additional context**
Thanks for your time

**Comment by Fox2Code** [comment]
This is how [BlurView](https://github.com/Dimezis/BlurView) works, it avoid refreshing itself when unnecessary.
This "bug" is likely an intended behavior, but I can check what can be done upstream if this really bother you.

**Comment by HiFiiDev** [comment]
> This is how [BlurView](https://github.com/Dimezis/BlurView) works, it avoid refreshing itself when unnecessary. This "bug" is likely an intended behavior, but I can check what can be done upstream if this really bother you.

Hi! Thank you for the reply and the link to the BlurView so I could see the code.  I would say do not worry about it as I may be the only one who this "bothers" (and bothers is putting it harshly!). Please do not worry about it as this is very minor and I believe your time could be spent doing something better :)

Thanks for creating the app.

**Comment by HiFiiDev** [comment]
Thank you!  Do you accept donations by chance?

**Comment by HiFiiDev** [comment]
> Blur is GPU expensive. I'm guessing Tensor isn't coping with the extra expense well, it's well known for heating and throttling.
> 
> Can you reproduce on another device?

Yes! That's always been. One interesting thing about blur views is that it is very intensive on the GPU, thank you for your comments and I'd be curious to see if anyone can reproduce

**Comment by Fox2Code** [comment]
Nah, app support blur on any Android 6+ device, I just don't allow it on Android 5 to avoid issues.

Device specific blur is for QuickStep/SystemUI for Android 12+ devices, and samsung implemented this on OneUI even earlier.
