### ISSUE TITLE
Could not acces either root or magisk

### ISSUE THREAD

**Issue by aioros57** [Fox2Code/FoxMagiskModuleManager#198]
**Describe the bug**
following update 6.2.0 I have the following message "Could not access either root or magisk" after rebooting the device

**Screenshots**
![Screenshot_20220826-151354_Fox's Magisk Module Manager](https://user-images.githubusercontent.com/90460028/188307582-5ebbbea8-debb-4280-91de-dba55d613208.png)

**Device info(please complete the following information):**
 - Device: [Samsung S10  exynos SM-G973F
 - OS:  Android 12  IU 4.1  G973FXXUFHVG4 (AUT)  magisk  25.2 (25200
 - App Version   0.6.2 {54)

**Additional context***

When I reboot my rooted S10, I open magisk is magisk not installed and zygisk, normally before the update rooting was present I am not the only one in this situation.

**Comment by Fox2Code** [comment]
Ok thx for issue, at this time there is not enough information to fix the bug.
I will try to do some modifications on the app to help self diagnose root issues.

**Comment by aioros57** [comment]
Hello fox2code, thank you if necessary my rooting breaks following the update after rebooting my S 10.

**Comment by Fox2Code** [comment]
Please confirm that this bug is still happening in `0.6.3`.

**Comment by aioros57** [comment]
Hello fox2code, good update, same concern, passage 0.6.3, see screenshot.
![Screenshot_20220906-082333_Fox's Magisk Module Manager](https://user-images.githubusercontent.com/90460028/188562407-128c5be2-3370-4744-a1ea-dabc2f10c16f.jpg)
![Screenshot_20220906-082348](https://user-images.githubusercontent.com/90460028/188562413-436927a2-d03d-4f8d-975f-1f85321ffa30.jpg)
![Screenshot_20220906-082149_Fox's Magisk Module Manager](https://user-images.githubusercontent.com/90460028/188562416-76d49d09-b873-4319-b06d-9c35df2ab2fc.jpg)
![Screenshot_20220906-082348](https://user-images.githubusercontent.com/90460028/188562467-aa0f7279-dbbb-4412-ab10-4291dd1abe03.jpg)
![Screenshot_20220906-082149_Fox's Magisk Module Manager](https://user-images.githubusercontent.com/90460028/188562473-53acc217-2168-4226-8e7c-68be3ef457ed.jpg)
![Screenshot_20220906-082333_Fox's Magisk Module Manager](https://user-images.githubusercontent.com/90460028/188562476-e3c3abf5-02cd-49dd-9b0f-ce75ade040d3.jpg)

**Comment by HuskyDG** [comment]
Are you root?

**Comment by aioros57** [comment]
Hello HushyDG, yes I am rooted with magisk 25.2 see capture there I just reflash for rooting. if each time there is an update of the manager that it does this, even m0han has this problem see on XDA the forum
![Screenshot_20220906-091515](https://user-images.githubusercontent.com/90460028/188570922-54d8d183-b236-4eff-92b1-8c52cfc78764.jpg)

**Comment by Fox2Code** [comment]
Is the app on DenyList/MagiskHide?
I will try to make error message more clear in next bugfix, and try to improve fallbacks for edge cases.

**Comment by aioros57** [comment]
Hello Fox2code, no the application is not hidden by magisk. This morning I again have the message "failure to access the root or magisk".
I don't understand I'm on version 0.6.3 since the update.

**Comment by Fox2Code** [comment]
@aioros57 I don't understand either.

**Comment by aioros57** [comment]
Hello Fox2code, I will see for the next update if the problem persists.
I'll keep you updated

**Comment by Fox2Code** [comment]
@aioros57 is the error message in `0.6.4` the same?

**Comment by aioros57** [comment]
Hello Fox2code, problem solved no more worries following the 0.6.5 update ok. Starting apppareil root present is also magisk.
