### ISSUE TITLE
[BUG] update module check bug

### ISSUE THREAD

**Issue by spookymyo** [Fox2Code/FoxMagiskModuleManager#199]
When I get a notification from Fox that there's a module update I couch the notification and it opens Fox. It does its quick update check but there are no updatable modules listed. I scroll through the list and there's nothing listed as updatable. So I have to manually go through every module to find the updates. This is happening every time I get an update notification.

 - Device: Unlocked Google Pixel 6 Pro
 - OS: Stock Android 12, rooted. 
 - App Version: 0.6.2

**Comment by Fox2Code** [comment]
Yeah, this is a bug, I think this has to do with my app using multiple thread and data being read as it's being written to it in memory, this bug will be fixed in `0.6.3`.

**Comment by Fox2Code** [comment]
Please confirm that this bug is still happening in `0.6.3`.

**Comment by Fox2Code** [comment]
Closing, assuming it is fixed in [`0.6.4`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/0.6.4) as I have no response.

**Comment by Fox2Code** [comment]
Please confirm it still exists in `0.6.4`, I will close this issues if I don't have a response soon.

**Comment by Fox2Code** [comment]
No response in a reasonable time, closing.
