### ISSUE TITLE
Sentry setup

### ISSUE THREAD

**Issue by IzzySoft** [Fox2Code/FoxMagiskModuleManager#200]
v0.6.2 added Sentry. Release notes are not entirely clear what default settings are configured: is it entirely opt-in, or is (some) reporting enabled by default? This question is also related to:

> Since new error reporting was added I need confirmation from F-Droid maintainers if anything needs to change

**Comment by Fox2Code** [comment]
v0.6.2 is not ready yet for F-Droid release, it's supposed to be opt-in for F-Droid and opt-out for GitHub release.

Due to a miss-configuration error sentry is reporting data unrelated to error reporting, this has already been fixed in source code.

I will keep this issue temporarily open until 0.6.3 get released.

**Comment by Fox2Code** [comment]
Also sentry is open source, and the links to it are here:
https://github.com/getsentry/sentry-android-gradle-plugin
https://github.com/getsentry/sentry-java

Sentry is only supposed to make request when the app crashes.
If it does send a request when app doesn't crash it need to be fixed ASAP.

**Comment by Fox2Code** [comment]
Sentry has completely been removed as it wasn't giving any useful crash report.
And the helper to upload proguard mappings isn't even working.
Sentry was taking almost 50% of the apk size.

I will try to find more privacy respectful alternatives that don't add 2Mb to apk size.
Sentry is just an open-source tracking library at this point.

**Comment by IzzySoft** [comment]
Thanks for your efforts! I was also asking because your app [is listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.fox2code.mmm), and my scanner alerted me about Sentry. So with Sentry being removed again, I can ignore that alert.

As for your search for a replacement, maybe [one of these hints](https://gitlab.com/-/snippets/1896503#acceptable-analytics) can help you? Concerning ACRA take care of the footnote, about the others I cannot tell much but they might be worth a look.

**Comment by IzzySoft** [comment]
Hi @Fox2Code, now that Sentry is back with the attached APK (which is used with my repo, see above) I need to re-ask: Is Sentry configured opt-in or active by default? And as we're on it: since FMMM is also available at F-Droid for quite a while, shall I rather remove it from my repo now?

**Comment by IzzySoft** [comment]
Thanks for the swift response! I was expecting that for the F-Droid releases (the release notes say as much) but was not sure about the Github one. Guess it makes not much sense keeping it in both repos (usually I remove an app after an overlap of 10..14 days of its appearance at F-Droid – I was just too lazy to uninstall and reinstall it on my own devices, which is why it's still there).

So unless you have some special needs to keep it listed with my repo, would you mind if I remove it there then? FOSS-folks can (and usually prefer to) get it via F-Droid.org anyway.

**Comment by IzzySoft** [comment]
OK, I take that as a "go" and will remove the app from my repo now (as I would usually have done within 2 weeks of its appearance at F-Droid.org). Should you for some reason want it listed again, just drop me a note. Thanks a lot for making your app available at F-Droid!

**Comment by Fox2Code** [comment]
@IzzySoft FoxMMM is LGPL, meaning you can fork it as much as you want as long as you publish the code of your fork.
I also removed Sentry from F-Droid variant because of past issue with privacy 
I configured it to not do any tracking on GitHub builds tho, but if I missed something that is privacy concerning please tell me.

GitHub sentry code:
https://github.com/Fox2Code/FoxMagiskModuleManager/tree/master/app/src/default/java/com/fox2code/mmm/sentry
F-Droid sentry code: (Stubs)
https://github.com/Fox2Code/FoxMagiskModuleManager/tree/master/app/src/fdroid/java/com/fox2code/mmm/sentry

**Comment by IzzySoft** [comment]
Thanks @androidacy-user! My updater informed me about the last update requiring the `Tracking` anti-feature because it detected Sentry having been added – which is why I came here. I don't see any urgency to keep the app in my repo, now that's available at "F-Droid proper" (at that point, given a decent overlap, I usually remove apps from mine unless it was explicitly requested to keep it for some reason or the other – so I'm neutral on this issue). I hesitate adding the `Tracking` AF to the app (that would violate the inclusion criteria, i.e. the "root + Tracking = NoGo" one).

So if you have reason I should re-establish it, I'd need an APK without Sentry inside at the tagged releases. If that's too much fuss, having the F-Droid build available to foss & privacy lovers IMHO should be sufficient (and thus no action required at your end). What do you think?

**Comment by Fox2Code** [comment]
@IzzySoft the F-Droid version should not contain Sentry, if F-Droid build contain sentry it's a bug, not a feature.

**Comment by Fox2Code** [comment]
@androidacy-user Sentry ping back-end for no reason by default, it is disabled on FoxMMM tho.

**Comment by IzzySoft** [comment]
Yes, that's how I understand it. To not put additional load on you having another build with Sentry being opt-in (while it's opt-out for Play and excluded for F-Droid), I'd say we leave it at the status quo. If you want me to re-establish it in my repo, I can do so with an opt-in variant – but I do not see any added value if the feature set is otherwise identical.
