### ISSUE TITLE
Support link

### ISSUE THREAD

**Issue by ale5000-git** [Fox2Code/FoxMagiskModuleManager#205]
Hi,
I wonder if there is any need to set support link with `mmm_exec setSupportLink` if it is already set in module.prop.
Or I'm missing something?

**Comment by Fox2Code** [comment]
`mmm_exec setSupportLink` allow to set an arbitrary support link at install, it override support link in the installation GUI.
Setting the support link only on the `module.prop` is usually enough tho.

**Comment by ale5000-git** [comment]
Ok, thanks.
