### ISSUE TITLE
[Bug] ChArch can't open prop or download module

### ISSUE THREAD

**Issue by n0101** [Fox2Code/FoxMagiskModuleManager#21]
![Screenshot_20220106-115920](https://user-images.githubusercontent.com/43557511/148421680-4a063f8b-56fa-48ff-ae82-32693b63d3ad.png)

Curl is accessible via user terminal but not su. 

Browsing ChArch repo the zip is in a different location than specified in the modules.json and readme.md is missing. 

https://github.com/Magisk-Modules-Alt-Repo/charch/releases/download/charch-v1.0/charch-magisk-module.zip is where it's located.

https://github.com/Magisk-Modules-Alt-Repo/charch/archive/master.zip is specified in modules.json

**Comment by Fox2Code** [comment]
Seems to be more of a module specific issue, neither `curl` or `patch` exist in Android or Magisk busybox.
Please report this to the [module specific issue page](https://github.com/Magisk-Modules-Alt-Repo/charch/issues) directly.

**Comment by Fox2Code** [comment]
You didn't provide any information related to your device and the error is a module related error not a manager error.
