### ISSUE TITLE
Have you ever considered some sorting options like Alphabetical & maybe some categories to sort by?

### ISSUE THREAD

**Issue by Jaladhjin** [Fox2Code/FoxMagiskModuleManager#226]
**Is your feature request related to a problem? Please describe.**
Not really no just some quality of life

**Describe the solution you'd like**
some sorting options like Alphabetical & maybe some categories to sort by

**Describe alternatives you've considered**

There aren't really any.

Thanks for your consideration even if it's just maybe Alphabetical sort since I'd imagine the categories would be more work.

**Comment by Fox2Code** [comment]
Alphabetical sorting is already a thing, and to do category sorting, modules categories should be assigned to each module first.
