### ISSUE TITLE
Shows module version from Magisk Manager repo, not installed version

### ISSUE THREAD

**Issue by bege10** [Fox2Code/FoxMagiskModuleManager#24]
I updated the module Riru - Clipboard Whitelist from Github to v13. The last version in Magisks repo is v11.
After reboot Magisk Manager shows the new version number, FMMM still shows v11.

![Screenshot_20220109-120330_Fox's_Magisk_Module_Manager](https://user-images.githubusercontent.com/1184237/148679666-da3941c3-5795-43d2-8b5b-d359b3e92849.png)
![Screenshot_20220109-120349_Magisk](https://user-images.githubusercontent.com/1184237/148679667-269e239e-b999-498b-b480-1288c050fa92.png)

**Comment by Fox2Code** [comment]
I see, thanks for reporting the issue, will be fixed in next app update!

**Comment by Fox2Code** [comment]
Does something like `v13 (v11)` instead of `v11` is this ok? So it show both local and remote version.

**Comment by bege10** [comment]
> Does something like `v13 (v11)` instead of `v11` is this ok? So it show both local and remote version.

I will understand this now, but perhaps other users not. Might "v13 (repo v11)" be more comprehensible?

**Comment by Fox2Code** [comment]
This will be "v13 (Last update: v11)" until next major release.
In next release it will be "v13 (Remote: v11)"
