### ISSUE TITLE
Can you follow the updates in Magisk module repo?

### ISSUE THREAD

**Issue by bege10** [Fox2Code/FoxMagiskModuleManager#25]
Developers still update their modules in Magisk Manager repo on Github. Currently I must search and install these updates manually.
Can you make FMMM to provide these updates?

**Comment by Fox2Code** [comment]
Will probably be hard to do on a case by case basis, the best would be to ask module developers to publish their modules to the [Magisk-Modules-Alt-Repo](https://github.com/Magisk-Modules-Alt-Repo), this app track both original repo and alt repo modules.

I will keep this issue open just in case I find something useful.

**Comment by bege10** [comment]
> Will probably be hard to do on a case by case basis, the best would be to ask module developers to publish their modules to the [Magisk-Modules-Alt-Repo](https://github.com/Magisk-Modules-Alt-Repo), this app track both original repo and alt repo modules.
> 
> I will keep this issue open just in case I find something useful.

I see. As long as there is no new stable Magisk Manager release that makes clear what will happen with this repo in the future developers seem just to continue with it. It is a pity that John Wu stopped that repo before there is a replacement.
We will see and meanwhile stumble through Github. 🤔

**Comment by bege10** [comment]
Thank you very much. And get well soon!

**Comment by Fox2Code** [comment]
It's been 3 years I think, soon is not an option, sadly.

**Comment by bege10** [comment]
I am sorry to hear that and I understand very well because in some way I am also affected. So I wish you all the best.

**Comment by Fox2Code** [comment]
Ok I did a lot of progress theses last few day, the next bugfix update will follow magisk repo updates!!!
(I have to use GitHub APIs to make sure to not re-download all `modules.prop` each database refresh)
Will probably be done in a few days as my health still make me slow to progress on thing, but at least I'm doing progress!

**Comment by Fox2Code** [comment]
Fixed in 0.2.7, if there is issue tracking updates just open a new issue.
It does a request to the GitHub API directly to get latest versions of modules.
It's simpler than doing a alternative Magisk repo mirror, and work fine!

**Comment by bege10** [comment]
> Fixed in 0.2.7, if there is issue tracking updates just open a new issue. It does a request to the GitHub API directly to get latest versions of modules. It's simpler than doing a alternative Magisk repo mirror, and work fine!

As v0.2.7 here doesn't show a difference between installed version and the one online of Riru clipboard whitelist it works!
You are fantastic!
