### ISSUE TITLE
Fdroid builds may crash

### ISSUE THREAD

**Issue by jhrush** [Fox2Code/FoxMagiskModuleManager#260]
On android 11 fox mmm 1.0.2 crashes immediately. I've tried clearing storage and cache of the fox mmm  app to no avail. I ended up reverting to 0.6.7

**Comment by TonyApuzzo** [comment]
Same on Google Pixel 7 Android 13 (TQ1A.221205.011)

**Comment by IzzySoft** [comment]
> Fdroid is notorious for slow updates

That was before the build server change. Currently, updates are coming almost daily. Still, a release cycle takes 2-3 days as F-Droid doesn't pull your APK but has to build it from your source.

> The GitHub version remains the flagship

Understandable. Still, people are told to use sources they trust – and they trust the F-Droid team as another layer to cross-check things :wink:

That said: APK size jumped by factor 10 with 1.x. May I ask what happened? Quite a difference between 3 MB with 0.6.7 and 30 MB with 1.0.2. Going by Github releases, the jump seems to have happened in 2 steps (and a little different sizes): 4.7 MB (0.6.7) => 15.4 MB (0.6.8) => 30.5 MB (1.0.2). The release notes give no clue. Could you please tell? Thanks in advance!

**Comment by licaon-kter** [comment]
@IzzySoft https://github.com/Fox2Code/FoxMagiskModuleManager/issues/234

**Comment by StormPooper** [comment]
Also happening on 1.0.3, running on Android 13. Uninstall and reinstall doesn't help, I have to revert to 0.6.7.

**Comment by TonyApuzzo** [comment]
Yes, same problem on 1.0.3

**Comment by licaon-kter** [comment]
F-Droid disabled 1.0.3 too, I guess https://github.com/Fox2Code/FoxMagiskModuleManager/pull/261 might fix it

**Comment by Fox2Code** [comment]
Please use scoop or logcat to provide crashes of F-Droid build.
Scoop: https://github.com/TacoTheDank/Scoop/releases
Logcat: https://developer.android.com/studio/command-line/logcat
