### ISSUE TITLE
CALLING ALL TRANSLATORS

### ISSUE THREAD

**Issue by androidacy-user** [Fox2Code/FoxMagiskModuleManager#264]
The following languages are going to be dropped if they don't get translated to a minimum of 60% in the next couple days:

- Arabic
- Arabic (Saudi Arabia)
- Chinese (traditional)
- Estonian
- Greek
- Italian
- Japanese
- Norwegian Bokmai
- Slovak
- Thai

The following languages are in danger of being dropped as they are close to <= 60%
- Indonesian
- Spanish
- Spanish (Mexico)

New languages are also welcome! And a huge thanks to everyone who has updated and/or contributed to translation so far, we ❤️ you!

The translation platform is @ https://translate.nift4.org/projects/foxmmm/foxmmm/#translations. We aim to release 1.1.x before next year, so please have your translations up to date by then!

**Comment by iParthDubey** [comment]
Hi, Can any one explain me the task ?

**Comment by xerta555** [comment]
> Hi, Can anyone explain me the task ?

Hi

As explained here: https://github.com/Fox2Code/FoxMagiskModuleManager#for-translators
2 possible ways:
- You create your account on nift4.org website, and you translate the project file into your language.
or
- You copy the `[app/src/main/res/values/strings.xml](https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/app/src/main/res/values/strings.xml)` file content into a new `app/src/main/res/values-YOUR-LANGUAGE/strings.xml` file, you translate it, in a new pull request (everything here, on github).

Personally i use the second method at each time for any project on Github.

**Comment by RealEthanPlayzDev** [comment]
> The following languages are in danger of being dropped as they are close to <= 60%
> - Indonesian

An update on this, see https://github.com/Fox2Code/FoxMagiskModuleManager/pull/288 for work in updating the Indonesian translation
