### ISSUE TITLE
erroneous entry of JamesDSP Manager module

### ISSUE THREAD

**Issue by bege10** [Fox2Code/FoxMagiskModuleManager#28]
I have this entry
![Screenshot_20220122-165322_Fox's_Magisk_Module_Manager](https://user-images.githubusercontent.com/1184237/150646154-dbec4bc5-baa7-486c-ba09-1962cd9b8c2d.png)

I guess it belongs to JamesDSP Manager module
![Screenshot_20220122-165304_Fox's_Magisk_Module_Manager](https://user-images.githubusercontent.com/1184237/150646185-3fe3e081-3091-4ac5-9987-f2b5d88bc244.png)

Magisk Manager does not show the erroneous entry.

**Comment by Fox2Code** [comment]
Fixed in 0.2.7
