### ISSUE TITLE
[BUG] Update Notifications

### ISSUE THREAD

**Issue by avisadius** [Fox2Code/FoxMagiskModuleManager#289]
**Describe the bug**

**To Reproduce**
1. Home screen and got new notifications
2. Click on notifications and showed ACCA Modules updated
3. Click on details and show it has last release 2022

**Expected behavior**
There's no update

**Screenshots**
![Screenshot_20230308-021028_Fox's_Magisk_Module_Manager](https://user-images.githubusercontent.com/44080415/223527383-cc489cad-a373-4d8b-aee3-69ba44ddb8d8.png)
![Screenshot_20230308-021034_Fox's_Magisk_Module_Manager](https://user-images.githubusercontent.com/44080415/223527399-d102f336-37c2-442d-bae6-5cc419b2b138.png)
![Screenshot_20230308-021137_Fox's_Magisk_Module_Manager](https://user-images.githubusercontent.com/44080415/223527403-b85aad87-1d73-4a48-9c34-65c329a1002c.png)

**Device info(please complete the following information):**
 - Device: Xiaomi Redmi 5a
 - OS: [Unofficial FlokoOS 3.0 Android 10]
 - App Version : Default release v.1.1.0 (64)

**Additional context**

**Comment by Hominine** [comment]
Reproducing this bug on a Pixel 5a and with the same app as well.   
  
Have tried reinstalling ACCA through a f-droid install, github repo, and the module manager itself to no avail.

**Comment by avisadius** [comment]
> Reproducing this bug on a Pixel 5a and with the same app as well.
> 
> Have tried reinstalling ACCA through a f-droid install, github repo, and the module manager itself to no avail.

yep, i know because ACCA are on hibernate right now, the owner said have no chance to get back project yet since september
![image](https://user-images.githubusercontent.com/44080415/224646508-ce168a17-c67b-4502-9226-5dbb4982305f.png)

**Comment by avisadius** [comment]
> Will investigate

thankyou veery much
