### ISSUE TITLE
Just for the sake of beauty 😉

### ISSUE THREAD

**Issue by bege10** [Fox2Code/FoxMagiskModuleManager#29]
Some languages (e.g German) need a bit more space 😀

![Screenshot_20220123-202458_Fox's_Magisk_Module_Manager](https://user-images.githubusercontent.com/1184237/150694803-f7986686-dc49-485c-a283-1e9371ffdc91.png)

**Comment by Fox2Code** [comment]
This is a language specific issues, in theory I could add a dependency to have resizable text components to fit in the box, but the best would be to change the translation directly to fit in the box IMO.

**Comment by bege10** [comment]
#33

**Comment by Fox2Code** [comment]
You fixed it! https://github.com/Fox2Code/FoxMagiskModuleManager/commit/ce18e5448d821a2e67612dd8ac879ef7e2741270
