### ISSUE TITLE
Convert from build.gradle to build.gradle.kts

### ISSUE THREAD

**Issue by RabehX** [Fox2Code/FoxMagiskModuleManager#297]
- **Due to the modernization and abandonment of the old traditional methods, it is necessary to make a shift** .

**Comment by Fox2Code** [comment]
This is not a valid argument to go to kotlin while groovy build.gradle work fine:
"Due to the modernization and abandonment of the old traditional methods, it is necessary to make a shift."

But, I'm not against giving kotlin build.gradle a shot, so @RabahX I'll be waiting for your pull request!
