### ISSUE TITLE
EULA link broken

### ISSUE THREAD

**Issue by IzzySoft** [Fox2Code/FoxMagiskModuleManager#298]
From the end of your Readme:

> The EULA can be found [here](https://www.androidacy.com/foxmmm-eula/). By downloading, installing, or using this app you agree to the terms of the EULA.

Some issues with that.

First, the link leads to a page one cannot even read that EULA without allowing a bunch of trackers, walking through a consent banner, reaching a security-error page – and finally end up on a page telling you "Oops! The policy is not here." Maybe there are some technical reasons causing this issue (I was using Tor browser as I didn't trust those third-party-inclusions – but there's also the fact that app.termly.io doesnt seem to allow embedding their page)

Second, doesn't such an EULA essentially make the app non-libre? I wonder how that fits with the LGPL license [you applied](https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/LICENCE)? That EULA restricts the use the license grants (I say so without having been able to read the EULA, as the license IMHO (IANAL) does not require my agreement to additional terms). I might be wrong here of course – just expressing my confusion.

**Comment by linsui** [comment]
I have to disable uBO to make that page work. Could you use a plain HTML page for that instead? That works on more browsers.

**Comment by IzzySoft** [comment]
PS: My confusion was just mitigated a bit when I found the proper URL and finally able to see the EULA at https://app.termly.io/embed/terms-of-use/5a2ec9c3-7f2a-41da-b5f7-db8e7e13b885 – so my fears of "non-libre" at least are gone seeing this:

![image](https://user-images.githubusercontent.com/6781438/229362569-5d6c6a19-c952-4374-b600-8d5ec43b1eb6.png)

Sorry, had to screenshot it as the page doesn't allow copying the text). That means the EULA only applies to downloads via Play Store – which was not clear from the Readme. So apologies for the confusion ***I*** might have caused with that part. I kindly ask to take my issue as a "question for clarification".

**Comment by IzzySoft** [comment]
Thanks @androidacy-user – that crossed with my comment. And yes, that answers my questions, thanks again!

If you wish to check: I tried accessing the EULA link from your Readme using (unmodified) Tor Browser on my Linux desktop, and was unable to get to the EULA as described (my "standard browser", a "hardened" Firefox, didn't succeed either). Not sure how that can be solved, though. I was, however, able to open the link provided with my previous comment just fine, even in my "standard browser" which (other than Tor) uses some protective addons (like uBO) – as that link does not require any 3rd-partly things. Maybe you could provide that link instead (or as an alternative)?

**Comment by LuccoJ** [comment]
I would like to triple-check: does the EULA apply to a custom build of the source code in this repository, and in particular to the build that [F-Droid provides in their main repo](https://f-droid.org/en/packages/com.fox2code.mmm.fdroid/) based on the source code it uses?

For indeed, the LGPL is designed to allow inclusion even in proprietary applications under some conditions, and anyway, as the application's author, you are free to apply any conditions on your code. However, it is important for the F-Droid project to understand whether they are distributing FOSS, as defined by themselves and by organizations like the OSI and FSF. Their users expect nonproprietary applications in the repository.

Therefore I would be grateful if you could clarify this matter, and that no term of the EULA that would potentially make the application nonfree under FSF and OSI understanding applies to users who get the app from F-Droid. In addition, for the convenience of F-Droid users having difficulty accessing the EULA, and for avoidance of confusion if it does not, indeed, apply to them, I would like you to clarify whether it would be okay to strip any reference of the EULA in a FOSS build of the app on F-Droid.

I ask all this mainly for the sake of clarity to users using the F-Droid build, and to avoid the F-Droid team being unclear on the legal status of the source code they build. Sorry for being so specific in my inquiries.
