### ISSUE TITLE
[request] Ability to just download modules instead of installing

### ISSUE THREAD

**Issue by nezorflame** [Fox2Code/FoxMagiskModuleManager#3]
Hi! Great app, thanks!

Can I submit a feature request? It'd be nice to be able to just download a module for future purposes. For me it's often the case that I don't need to install the module right now, and some modules don't need to be installed at all except for some special cases (like TWRP Retention Script one).

**Comment by Fox2Code** [comment]
Yeah, about that, the format of module is not always what you expect them to be.
By that I mean the module are formatted like Code -> Download ZIP

This mean there is a `ProjectName-branch/` prepended to the module zip entries.
Ex: getting `ProjectName-branch/customize.sh` instead of `customize.sh`
This is also why there is a patch step after the module download.

The question I'm asking to myself is what I should do with semi-malformed modules.
Since topjonwu replace the `install-binary` some modules have invalid, outdated or no binary at all.

My module manager execute directly [`module_installer_compat.sh`](https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/app/src/main/assets/module_installer_compat.sh) with a patched zip,
so it doesn't care about neither `install-binary` or `install-script`.

So should I replace `install-binary` unconditionally with the compatibility script, or should I do this differently?

**Comment by nezorflame** [comment]
I'd prefer sticking to the Magisk's approach unless we have some pros to the other method.

**Comment by Fox2Code** [comment]
Magisk does similar than my app already does, I can either use my compatibility script that can allow better legacy Magisk support, or just use the official script.
Fox's MMM support script minimum Magisk support is 19.0+
Magisk official script minimum Magisk support is 20.4+

Note: My modified script also contain some fixes for old Magisk versions.

**Comment by nezorflame** [comment]
I see.

In this case I'd say it's up to you - I know neither how many people use Magisk on older OS versions nor how many users you've got right now that need improved compatibility.

If both of the numbers are low, might be better to stick to the official script.

**Comment by Fox2Code** [comment]
Well my script behave exactly like the official on the latest Magisk version so whatever.
If I support such a low Magisk version it's because I like compatibility, even if it's pointless.
This feature will be there in 0.3.0, just need fix anything else first.

**Comment by nezorflame** [comment]
Gotcha, thanks!

**Comment by Fox2Code** [comment]
Ok I came up with an idea, the module manager may use `minMagisk` to determine if it should use the compatibility script or not.

`grep_get_prop` function was introduced in Magisk 21.2, and the compat script insert it if it is missing.
So if `minMagisk` is less than `21200` it use the compat script, else it use the official Magisk script.

There is no point inserting a compat script if the Module is not compatible with the Magisk version the compat help.
The only thing the script do is helping modules install on old Magisk versions, it doesn't force them.
Modules will always have the final say in whatever they want to be installed or not.

I also think it will motivate modules makers to define `minMagisk`, I made a developer documentation [here](https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/DEVELOPERS.md)

**Comment by osm0sis** [comment]
The presence of customize.sh should also signify a modern Magisk module that won't need the compat script. 👍

**Comment by Fox2Code** [comment]
Well, the compat script is to help modern Magisk module to install on old Magisk versions.
It doesn't do anything to help install old modules on modern Magisk version, as the official script already do that pretty well.
(Note: The compact script behave exactly like the official one on Magisk 21.2+)

**Comment by Fox2Code** [comment]
Also sorry for taking a lot of time to respond, I was not feeling very well today.

**Comment by nezorflame** [comment]
No worries, and thanks again for your work!

**Comment by stylemessiah** [comment]
Looking forward to download option as i use local installs all the time, and like to backup modules....

**Comment by Practicalbutterfly5** [comment]
+1 for this feature.
I would simply like to see the source code of the module, before installing, Just to get an idea, of how the module works.

**Comment by Fox2Code** [comment]
Implemented in [`3.0.0-dev1`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/3.0.0-dev1)

It just open the web browser with the download URL, and for Androidacy, it's still WIP.

My app can handle installing GitHub zips from storage, so it's fine.

**Comment by stylemessiah** [comment]
The downloaded zips are the master zips (like downloading the srouce.zip from a release), so contain a subfolder and wont work if people try and install via Magisk Manager

It would be better if the release zip was downloaded to make install universal across Magisk Manager and Fox MM?

**Comment by Fox2Code** [comment]
@stylemessiah fixed in #49
