### ISSUE TITLE
[BUG] Installing any module results in crashloop

### ISSUE THREAD

**Issue by parknich** [Fox2Code/FoxMagiskModuleManager#308]
**Describe the bug**
When attempting to install any module, it results in FMM crashing every time you open it. You have to reset the app to get it to work.

**To Reproduce**
1. Go to modules
2. Install a module
3. See error

**Expected behavior**
The module installs correctly and does not result in a crasshloop

**Screenshots**
![Screenshot_20230427-132434_Fox's Magisk Module Manager](https://user-images.githubusercontent.com/45834520/234941363-d47b0322-9426-4ea6-9ed5-426f1da1309f.png)

**Device info(please complete the following information):**
 - Device: OnePlus 7T HD1907 [HD1905]
 - OS: LineageOS 20 for hotdogb
 - App Version 67

**Additional context**
[logs.txt](https://github.com/Fox2Code/FoxMagiskModuleManager/files/11346481/logs.txt)

**Comment by SonOFSam666** [comment]
![Screenshot_20230427_115802_Fox's Magisk Module Manager](https://user-images.githubusercontent.com/131947820/234951980-558adf9a-3a15-41f0-9453-218413ede3b1.jpg)
I also have this issue
