### ISSUE TITLE
Incomplete version name

### ISSUE THREAD

**Issue by bege10** [Fox2Code/FoxMagiskModuleManager#31]
For this module Fmmm shows an incomplete version name

![Screenshot_20220123-205100_Fox's_Magisk_Module_Manager](https://user-images.githubusercontent.com/1184237/150695627-c2112213-450e-4190-ab8c-f08916d26df4.png)

Compare with Magisk Manager

![Screenshot_20220123-205122_Magisk](https://user-images.githubusercontent.com/1184237/150695644-8f31f982-a936-49d8-917c-65439c60bc03.png)

**Comment by Fox2Code** [comment]
This is the results of a feature because some module use insanely long version names, to display version name in a usable way, the app use the version code if the version name is too long.

**Comment by bege10** [comment]
At least in this case this is not user friendly because in the repo the release version is 26.1.4. So one has not comparable version names.
I don't see a problem with the "insane" version name, it is well displayed in Magisk Manager.

**Comment by Fox2Code** [comment]
The problem is that too long version names can overflow on the user interface, I will apply a similar fix to the one you proposed.
