### ISSUE TITLE
[BUG] Simplified Chinese option not work

### ISSUE THREAD

**Issue by Z-Siqi** [Fox2Code/FoxMagiskModuleManager#320]
**Describe the bug**
English is still displayed after Simplified Chinese is selected

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Language'
3. Scroll down to '中文'

**Screenshot**
![20230503_073654](https://user-images.githubusercontent.com/77391690/235807616-131f0512-29dc-427d-9df7-d23e453c5c61.gif)

**Device info(please complete the following information):**
 - Device: [Pixel 7 Pro]
 - OS: [Android 13]
 - App Version [2.0.2]

**Comment by androidacy-user** [comment]
We're investigating what we suspect is a issue with RossetaX internally. We will migrate this issue to https://github.com/Androidacy/MagiskModuleManager in the meantime

**Comment by Z-Siqi** [comment]
> We're investigating what we suspect is a issue with RossetaX internally. We will migrate this issue to https://github.com/Androidacy/MagiskModuleManager in the meantime

I just found another way could fix this error, change the `values-zh-rCN` folder name to `values-zh` can fix it.

````
app/src/main/res/values-zh-rCN/strings.xml
````
To
````
app/src/main/res/values-zh/strings.xml
````
