### ISSUE TITLE
module info with screenshots

### ISSUE THREAD

**Issue by vg21c** [Fox2Code/FoxMagiskModuleManager#34]
i think it would be better if we could click on module and see its info, screenshots (like it has ios jailbreak)

for info and screenshots use readme.md

example from ios:
![sileo-01](https://user-images.githubusercontent.com/63352606/150815447-180b74bd-be41-4804-834b-939a1fc91447.jpg)

**Comment by Fox2Code** [comment]
Hum, the app already have a button to show the `readme.md` and see the module information.
I feel you are asking for already existing features.

Please be more specific, as I may have not have fully understood what you are asking me to do.
If you are asking to to fully change the look of my app, I will not do that. (I do not have enough time to do this)

But if you are asking for some minor changes I will be happy to discuss about that.

**Comment by Fox2Code** [comment]
Note: Invalid doesn't mean issue is denied, this mean I lack some information to fully understand the issue.
The tag will be removed as soon as I understood what you want me to change in the app.

**Comment by vg21c** [comment]
I mean, in IOS case when you click on module button it has inbuilt readme.md which is fetched from Github. (if i'm not wrong it called iframe) so it's easy to see how module looks.

in screenshots which i've sent here, we're looking readme.md of module below details and changelogs button.

if you could to do it, it would be great

**Comment by vg21c** [comment]
from user side it's little bit hard to click on static  github link and check all repositories with links (when you're searching good new modules)

when you're clicking on module and it has install button, information, screenshots on same page, it makes everything more easy

**Comment by Fox2Code** [comment]
It's up to module makers to add their screenshot.
It's not the manager work to do that.
Markdown have a documentation.
Also I'm not redesigning the app for now, I'm already struggling with the current UI.
