### ISSUE TITLE
Incomplete search results

### ISSUE THREAD

**Issue by bege10** [Fox2Code/FoxMagiskModuleManager#36]
When I search for binaries or binary I enter "binar".
As a result I only see "Cross Compiled Binaries".
"Nano for Android SDK", "ADB & Fastboot for Android NDK" and others that contain "binaries" in the description are missing.
So I thought Fmmm only searches in the names, not the descriptions.
But when I enter "audio" I see "AirMusic - stream you music!" in the results (the search term is not in the name but in the description) but not "USB Samplerate Unlocker" which also has "audio" in the description.

So I don't understand where the Fmmm is looking for the search term. I would like Fmm to search for the search term in both the name and the description as Magisk Manager 23.0 does.

**Comment by Fox2Code** [comment]
Fox's Mmm currently doesn't search in descriptions, I may add that in a future version where it also scan the description.

**Comment by bege10** [comment]
> Fox's Mmm currently doesn't search in descriptions, I may add that in a future version where it also scan the description.

Why does Fmmm find  "AirMusic - stream you music!" when I search for "audio"?

**Comment by Fox2Code** [comment]
Fox's Mmm currently scan module name and module id, the module id probably contain music in their internal id.

**Comment by Fox2Code** [comment]
New system rank depending on how well the app think the module match the search query.

A `filterLevel` is set in `matchFilter`, the lower the filter, the better the app think the module match the query, so more relevant results appear first.

`0.3.0` will be a big update!
