### ISSUE TITLE
"Your current file picker failed to give access to the file." toast when attempting to install module from local storage

### ISSUE THREAD

**Issue by Dionicio3** [Fox2Code/FoxMagiskModuleManager#37]
![Screenshot_20220126-025347_Fox's_Magisk_Module_Manager](https://user-images.githubusercontent.com/61460279/151150900-ddd39d85-fa4b-44fb-84d7-8a73d8f328b0.png)
Hey I get this error whenever trying to install a module from my downloads folder. I'm currently using a OnePlus 9 Pro on the latest build of LineageOS.

**Comment by Fox2Code** [comment]
Hi, I already heard issue with this feature before, the message you are seeing is a direct result of a piece of code that scan for error like this.

I made a debug build: [debug.zip](https://github.com/Fox2Code/FoxMagiskModuleManager/files/7942753/debug.zip)

Please test again with the debug build, and attach the logcat linked to.
(If you don't know how to do that there are a lot of tutorial on the internet on how to use adb)
`adb logcat > logcat.txt` should work and then type `Ctrl + C` to stop the log recording.

The debug build match this commit: 
https://github.com/Fox2Code/FoxMagiskModuleManager/commit/b81509dd32c78da451e5e371f352598c3900b421
