### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by ThePrimalPea** [Fox2Code/FoxMagiskModuleManager#38]
Create a support Telegram channel so the community will much more easier to help improving the app.
Also leave a instruction where the translators can send their translations to you

**Comment by Fox2Code** [comment]
Yeah I was thinking of making a telegram support channel, I send it to you once I have created it.

**Comment by Fox2Code** [comment]
I think I will not advertise this link a lot until I have a basic moderation team: https://t.me/Fox2Code_Chat

**Comment by Fox2Code** [comment]
The commit [`Add telegram chat link to the app.`](https://github.com/Fox2Code/FoxMagiskModuleManager/commit/8995f2757c7af692f28e6fa156eb866eaca678ab) resolve this issue.
