### ISSUE TITLE
[Suggestion] add a CANCEL button.

### ISSUE THREAD

**Issue by samyak039** [Fox2Code/FoxMagiskModuleManager#45]
the magisk installer has a cancel button which can be used to cancel or stop the installation, I know it works only if pressed before the actual installation starts, but it's a solution to accidental pressing of download/install button (as I mentioned [here](https://github.com/Fox2Code/FoxMagiskModuleManager/issues/39#issuecomment-1024971327)).

**Comment by Fox2Code** [comment]
I plan an UI rework to implement partially or completely #3, #26 and #39.

A cancel button is not really easy to make in the current state of the app.

**Comment by samyak039** [comment]
I guessed so :)

btw thanks for the app, it is a great app. and it really fill the gap left behind.
