### ISSUE TITLE
Updated module not showing as updated - but one that wasnt is...

### ISSUE THREAD

**Issue by stylemessiah** [Fox2Code/FoxMagiskModuleManager#46]
Alt-Repo's json recognises the change (from 2.6 to 2.7)

Your last-update epoch date for the module is correct in modules.json, i checked

Fox MM shows the old version (2.7)

Meanwhile it shows another module of mine, which i havent touched (in 20 days) shows as updated on todays date (same as non working updated module)...doesnt show as updated in Alt-Repo's json btw

Also while im here, had a friend who submitted a new module the other day and his Fox MM couldnt see it at all, while it showed on mine....and yes, he cleared data and even reinstalled.

**Comment by Fox2Code** [comment]
Ok thank for reporting, I think I know why this is happening, I will do a fix for that.

**Comment by stylemessiah** [comment]
Cheers mate, good luck and thanks!

**Comment by Fox2Code** [comment]
Next release it should show up, I will speed up the next dev build because of this bug.
Thanks for reporting the bug, you are the best!

**Comment by Fox2Code** [comment]
Pinning issue until next release.

**Comment by stylemessiah** [comment]
> Next release it should show up, I will speed up the next dev build because of this bug. Thanks for reporting the bug, you are the best!

Thanks champion

**Comment by Fox2Code** [comment]
Fixed in [`3.0.0-dev1`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/3.0.0-dev1) but will still keep this pinned until `3.0.0` comes out.

**Comment by Fox2Code** [comment]
Clear cache to fix issue if the problem persists after update.
