### ISSUE TITLE
I have a problem with v3.0.0

### ISSUE THREAD

**Issue by ender-zhao** [Fox2Code/FoxMagiskModuleManager#48]
App crashes when Busybox module is installed

**Comment by ender-zhao** [comment]
https://user-images.githubusercontent.com/77391690/152137545-b2fffc4e-4492-4e06-9402-2ec52ecbd2f7.mp4

**Comment by Fox2Code** [comment]
It's a dev version, I have rushed it's release, but it's for testing will be fixed really fast.

**Comment by Fox2Code** [comment]
Should be fixed in [`0.3.0-dev2`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/0.3.0-dev2).
