### ISSUE TITLE
Updated addons cannot be installed

### ISSUE THREAD

**Issue by gjf** [Fox2Code/FoxMagiskModuleManager#49]
FoxMmm-0.2.9 issue.
I have observed update for LSPposed two times already and each time I cannot install it inside Manager:
![Screenshot_20220203-164245](https://user-images.githubusercontent.com/322186/152355018-0c33906d-6e38-46f8-883f-4755bc7e11a3.jpg)
![Screenshot_20220203-164253](https://user-images.githubusercontent.com/322186/152355036-e0a3eafe-d348-4855-805f-dcbb61def081.jpg)

**Comment by Fox2Code** [comment]
Fixed!
