### ISSUE TITLE
Fail to connect to the internet

### ISSUE THREAD

**Issue by aaref1234** [Fox2Code/FoxMagiskModuleManager#5]
Hi .

When you open the application, the message “Fail to connect to the internet” appears, knowing that the Internet is good . 
 
Thank you .

**Comment by Fox2Code** [comment]
“Fail to connect to the internet” mean the app doesn't have access to the internet...

It's meant for the user to fix that, please check your system setting and if you have any firewall apps that conflict.

Please also give more information about your device. (Android version, Stock/Custom ROM) 

Also does this issue appear on pre release versions of the app?

I really want to help you fix the issue but you are not giving me enough information here.

**Comment by aaref1234** [comment]
Galaxy Note 9
Android 10 
App Version 0.1.2

**Comment by Fox2Code** [comment]
Please try the latest pre-release to see if it fix your issue:
https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/0.2.0-pre3

With the very low amount of info you gave me, I can't guarantee it will work.
If it doesn't work please send a logcat with the error in it.

**Comment by aaref1234** [comment]
![Screenshot_٢٠٢١١٢٠١-٢٣١٩٥٩_Fox's Magisk Module Manager.jpg](https://user-images.githubusercontent.com/62560435/144307845-dcbd5636-e292-4813-9903-9610149b1da1.jpg)
![Screenshot_٢٠٢١١٢٠١-٢٣٢٠١٧_Settings.jpg](https://user-images.githubusercontent.com/62560435/144307861-3adac783-f7ac-4864-925d-dfa948f4140a.jpg)

**Comment by Fox2Code** [comment]
Ok thank I think I have an idea why this error occur, some locales have problems with the `toLowerCase` and `toUpperCase` functions.
Can you try to put your phone local in English, test the bug and tell me if the bug is still happening.
I will try to do a fix for that in `0.2.1`, but I can't guarantee it will work completely as this can be an issue caused by libraries (code I do not control).

**Comment by aaref1234** [comment]
I changed the language of the device and and the same error occurred . 

Thank you .

**Comment by Fox2Code** [comment]
Well I have no idea what this is happening then.
You can try sending a logcat using a debug build.
I have a debug build here:
[FoxMmm-0.2.0-debug.zip](https://github.com/Fox2Code/FoxMagiskModuleManager/files/7638058/FoxMmm-0.2.0-debug.zip)
The platform tools can be downloaded here:
https://developer.android.com/studio/releases/platform-tools
`adb logcat > logcat.txt` reproduce the error, and then close the terminal.
It should create a logcat with the debug logs, using the debug build should help identifying the issue.

**Comment by aaref1234** [comment]
Why does the "online repo" not exist?

**Comment by Fox2Code** [comment]
the "Online repo" element isn't added to the list if there is no element to show.
Due to the app failing to connect to internet, it can't collect the module list.
Please provide a logcat if you can, because I have no clue why this is happening to you.

**Comment by aaref1234** [comment]
[logs-٢٠٢١-١٢-١٤-٠١-٢١-٣٤.zip](https://github.com/Fox2Code/FoxMagiskModuleManager/files/7707344/logs-.-.-.-.-.-.zip)

Are these files required ?

**Comment by Fox2Code** [comment]
The log-cat you sent said nothing useful about the connections errors, I will try to see what I can do to display the crash-log directly in-app in a future version.
My health is not stable, sorry again if I do not do things very fast.

**Comment by aaref1234** [comment]
[logs-٢٠٢١-١٢-١٦-١٧-١١-٤٠.zip](https://github.com/Fox2Code/FoxMagiskModuleManager/files/7727979/logs-.-.-.-.-.-.zip)

Another file I hope you will try it .
I apologize for the inconvenience and wish you good health .

**Comment by Fox2Code** [comment]
<https://github.com/Fox2Code/FoxMagiskModuleManager/releases> I put a debug version in the latest release.

**Comment by Fox2Code** [comment]
I think logcat isn't showing anything because you are not using a debug version, I think this should help.

**Comment by aaref1234** [comment]
[logs-٢٠٢١-١٢-١٩-٠٣-٣١-٠٦.zip](https://github.com/Fox2Code/FoxMagiskModuleManager/files/7740156/logs-.-.-.-.-.-.zip)

**Comment by aaref1234** [comment]
I know the cause of the problem 

I tried vpn connection USA and the problem was solved .

My site is in Saudi Arabia .

Can you fix the site problem ? 

Thank you 😊 .

**Comment by Fox2Code** [comment]
Ok, it's probably a country based firewall that is blocking the way the app work.

At this point there isn't that much I can do, I will still try to find a workaround for this specific issue if possible.

**Comment by Fox2Code** [comment]
Latest release should help with your connectivity issues, I do not consider this a fix, but it should help.

**Comment by aaref1234** [comment]
I tried the latest version and the problem is not resolved .

**Comment by Fox2Code** [comment]
Is the bug still there or is it fixed?

**Comment by aaref1234** [comment]
The problem has been resolved .

Thanks .

**Comment by aaref1234** [comment]
I have uninstalled and reinstalled the app and the same problem appears as before !

I have tried more than one version of the application and the same problem "internet connection failed" occurred .

And when I try to download any module it shows download error .

**Comment by Fox2Code** [comment]
I can't just "get around state firewalls" like nothing happens, I added a DNS caching feature so if you use a VPN once the app will cache the IPs of the domain names and will use these cached values if no DNS request can be made.

I will introduce new option for the next release of the app that should help users workaround those issues.

**Comment by Fox2Code** [comment]
Disable "Dns over https" and it should fix your issue, it's still enabled by default.

This is a new option that was added in [`3.0.0-dev1`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/3.0.0-dev1)!
