### ISSUE TITLE
Failure when changing orientation?

### ISSUE THREAD

**Issue by gjf** [Fox2Code/FoxMagiskModuleManager#50]
Not sure it is a bug actually...
Whatever: can anybody try to enable changing view orientation on the phone - and just turn the phone from vertical to horizontal during installation?
In my case it causes "failure when unpacking the module" during installation from local repository.

Just in case: the module I have attached has about a few seconds from the start of install till the finosh - so one who wants to test has enough time to rotate the phone and to check.
I really believe it was just a occasional case but who knows.
[acc_2022-02-03_14.16.05.zip](https://github.com/Fox2Code/FoxMagiskModuleManager/files/7997241/acc_2022-02-03_14.16.05.zip)

**Comment by Fox2Code** [comment]
I always have orientation changes disabled, I will fix this ASAP.
