### ISSUE TITLE
Cannot undo installation of module BEFORE reboot

### ISSUE THREAD

**Issue by gjf** [Fox2Code/FoxMagiskModuleManager#51]
The current stable release of Manager does not allow to undo installation of the module before reboot.

Let's assume: I installed module 1. Then before reboot I found module 2 that is better than module 1. So I install module 2 and before reboot I want to delete module 1.

At present - it is not possible so two reboots are necessary.

**Comment by Fox2Code** [comment]
Is it already possible, I just suck at making UIs, if the bin have a cross and you long press it, you can insta delete a module just after installing it if the install wasn't an update.

Keeping open because I need a better UI for this.

**Comment by gjf** [comment]
I'll be honest with you: I did not see changes in bin icon from the first time when deleting module :)
So I have to admit we need to change something in UI.
Maybe adding some colours?

**Comment by Fox2Code** [comment]
Yeah I can do that for `0.3.0`, but it will need a better UI in the future.

**Comment by Fox2Code** [comment]
Yeah no I fully fixed it I think, button is red, default action is full clear now instead of normal clear when available.
