### ISSUE TITLE
Download problems

### ISSUE THREAD

**Issue by GERDominik165** [Fox2Code/FoxMagiskModuleManager#53]
I cant download any module

**Comment by Fox2Code** [comment]
Your are too vague and too short, please be more descriptive in you bug report.

Things like screenshot or short videos are a great way to show the problem.

Also add the maximum information as possible, like what Android version are you running, do you use a VPN or a Firewall.

I'm closing this issue, but please feel free to open a new one if you feel like giving more information describing the issue.

**Comment by GERDominik165** [comment]
I don't use VPN and i don't have settet up a firewall , because i go in your APP to the modules , i tryes to download anythink i wait the 10 seconds to wait for download , then nothing changes nothing downloads sry for my Bad eng. But i try to help

**Comment by GERDominik165** [comment]
I can upload a short screen Video in yt unlisted only for you to See what i mean is that okay ?

**Comment by GERDominik165** [comment]
https://youtube.com/shorts/gF1daYZ9ITA?feature=share

**Comment by GERDominik165** [comment]
And sry thats my first feedback on github ^^

**Comment by GERDominik165** [comment]
I have open the Website from where the downloads are in Browser there can i download all
