### ISSUE TITLE
 Androidacy’s module listings broken with deceptive ads in their place. 

### ISSUE THREAD

**Issue by NestaYor** [Fox2Code/FoxMagiskModuleManager#56]
Maybe consider anyone else besides Androidacy.

"Because Android deserves better." 
![Screenshot_20220205-202019_Fox's Magisk Module Manager](https://user-images.githubusercontent.com/45150937/152664509-20f427e4-6014-416a-ad26-7848eb6388aa.png)

**Comment by Fox2Code** [comment]
The Androidacy integration is not ready yet, but rest assure if Andoridacy is becoming a problem I will not hesitate to remove their repo from my Manager.

In the meantime you can disable Andoridacy repo in: **Settings** -> **Manage Repos**

**Comment by Fox2Code** [comment]
If the integration was complete #26 would be already closed.

**Comment by Fox2Code** [comment]
Closed by [`0.3.0`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/0.3.0)
