### ISSUE TITLE
Improving inclusion criteria for repos

### ISSUE THREAD

**Issue by Sei-lus** [Fox2Code/FoxMagiskModuleManager#59]
https://github.com/Fox2Code/FoxMagiskModuleManager#i-want-to-add-my-own-repo

I want to propose the following amendment to this:

"Modules in the repo must be monitored, and malicious modules must be removed."

To: And modules can't be edited (including original readme.md) and repackaged as the same module or an updated version.

---------------------------------

And want to additionally propose:

-Authors must have given their consent or publish themselves to be on the repository; otherwise if they ever ask to be removed from the repo the repository owner should comply.
-Authors that gave their consent, can withdraw it in the future completely if the repository guidelines or behavior changes. If the repository behaves as they originally did, then the author may opt out of future updates getting added and not his old work.
-Repo should be free of revenue to host other authors work without permission. If they have ads or Patreon or similar for premium modules, then they can't publish free xda work from other authors that aren't even aware of it.
-Repo should adhere to the download format of the fox's mmm app with a direct download for quick updating.
-If repo has ads, then they shouldn't be deceiving (i.e a second download button, or a link to something that almost look like a module, etc)
-Repo can't collect personal user data, or metadata.

**Comment by Fox2Code** [comment]
Yeah, I think it's a good idea., it's just a written thing, but it's should work.
I may not take all of them, but most seems ok.

**Comment by Sei-lus** [comment]
I am also writing from mobile on the street so I'll try to come back and clean it up a bit later on the PC so it makes a bit more sense. Thank you!
