### ISSUE TITLE
Layout: Move the install module from local file button to the top of the app.

### ISSUE THREAD

**Issue by Sei-lus** [Fox2Code/FoxMagiskModuleManager#60]
Move the button to search for a local file to install from the bottom of the installed modules, to the top.

Due to not wanting to use Androicy I went to manually update my apps, and noticed for the first time how difficult it is compared to Magisk Manager official app to install from local on your app. I have more than 20 modules loaded so that's the reason why.

That said the main issue besides position and convenience is this: 
![IMG_20220206_150921](https://user-images.githubusercontent.com/57790936/152697343-1753b4f0-4c4f-493c-9dfe-2e7c66567572.jpg)

The button itself is not noticeable.. by not being at the bottom of everything you can't just scroll to the end, so you have to precisely go to the middle or wherever the amount of modules installed puts it in. So maybe highlighting it and leaving it where it is may be a second option.

**Comment by Fox2Code** [comment]
This has been requested so many times, I will make this the default.

**Comment by Sei-lus** [comment]
No. Download location for downloaded files at 77.
Here to put the "install from local files" to the top of the modules list, instead at the bottom.

**Comment by DerGoogler** [comment]
Made in [841e414](https://github.com/Fox2Code/FoxMagiskModuleManager/pull/107/commits/841e414b6e4dcfc3b8cb7834a45e2ebdd3fa1f9d)

**Comment by DerGoogler** [comment]
This can also be closed
