### ISSUE TITLE
Download Module results in parse error

### ISSUE THREAD

**Issue by pixincreate** [Fox2Code/FoxMagiskModuleManager#66]
As stated above, Download Module` option in FoxMagiskModuleManager downloads the `.zip` which we users call `module` from [here](https://github.com/Fox2Code/FoxMagiskModuleManager/archive/refs/heads/master.zip)(example) that needs to be extracted, opened, and and needs to recompress the files in order to be able to flash in Magisk later on.

However, I do think it is possible to download from releases section if it exists with a condition to check whether it exists or not as some devs just don't release but update the repo.

What's your view on this?

**Comment by Fox2Code** [comment]
Yeah, the modules are downloaded in their original format and not tampered with when downloading them.

So many modules are in the GitHub.zip format and not in the Module.zip

My manager handle both formats, but it's not the case for Magisk Manager

**Comment by pixincreate** [comment]
> My manager handle both formats,

So, it is possible to save the github.zip in module.zip format upon hitting download module.   
I'm pretty much new to Android coding world. If you can guide me a little, I can put up a pull request in the mean time... You can ignore if not interested to.

**Comment by Fox2Code** [comment]
My app auto convert github.zip format to module.zip format on install.
