### ISSUE TITLE
Layout: add margins to the sides of text that touch the edge of the screen

### ISSUE THREAD

**Issue by BloodRaven0** [Fox2Code/FoxMagiskModuleManager#67]
Especially when opening the info panel on modules, the text is physically touching the edge of the screen, which is a big no-no from a design standpoint, because some phones have those stupid curved edges and some (like mine) have screen protectors with black edges that cover the first and last 20 or so pixels at the edges, making text that touch the edge very difficult to read.
Add a 40-50 pixel margin to be safe.

**Comment by Fox2Code** [comment]
Yeah I think I could do a quick fix, Fox's Mmm is my first application with complex UI, so it is not very clean.

(See my cry for help here #39)

**Comment by BloodRaven0** [comment]
@Fox2Code for a first application with complex ui, you're doing pretty well! Also a lot of apps are guilty of not respecting edge margins, so don't feel too bad for forgetting it. Good luck with your app! ❤️

**Comment by Fox2Code** [comment]
Please test [`0.3.2`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/0.3.2) and tell me if it's enough for you.

**Comment by BloodRaven0** [comment]
Yes, it does seem a lot better. For my device it's fine, but I can't speak for other devices. Thanks for the quick fix! ❤️

**Comment by Fox2Code** [comment]
K I close the issue then, if someone else have the same issue please open a new one.
