### ISSUE TITLE
Broken "Force English language" option

### ISSUE THREAD

**Issue by VladWinner** [Fox2Code/FoxMagiskModuleManager#71]
For some reason the app language changes to English only if OS default language is English. "Force English language" option is ignored.

Here are the references I found in the code:

CompatConfigHelper.java
boolean `forceEnglish`

MainApplication.java
boolean `isForceEnglish`
`.getBoolean "pref_force_english"`

SettingsActivity.java
`compatThemeWrapper.setForceEnglish`

root_preferences.xml
```
app:key="pref_force_english"
app:title="@string/force_english_pref"
```

strings.xml
`string name="force_english_pref"`

---
Device: Samsung Galaxy S20 FE Snapdragon, One UI 4.0
Android version: 12
App version: 0.3.1

**Comment by Fox2Code** [comment]
I don't know how to implement this, please help!

**Comment by Fox2Code** [comment]
If not one help me I'll just remove the option.

**Comment by Fox2Code** [comment]
"Force English language" will be removed as I am unable to implemented a I received no help from the community.

Sorry if you really wanted this feature but I am unable to implement it.

**Comment by VladWinner** [comment]
Don't worry about it. Personally, I don't use this feature, I just wanted to report a bug. Perhaps in the future there will be a person who can help.
