### ISSUE TITLE
Magisk-Module-Repo modules out of date.

### ISSUE THREAD

**Issue by Fox2Code** [Fox2Code/FoxMagiskModuleManager#72]
The Magisk module repo stopped updating it's json index the 21 December 2021.
(May vary off by one day depending on timezone)

I got complain about outdated links, and module versions.

A workaround is work in progress, if it doesn't work, I will remove it completely from the repo.

**Comment by coxackie** [comment]
What is anyway the point of this old official repo since all activity is now in the alt one?

**Comment by Fox2Code** [comment]
To keep an archive of old modules, but if enough modules transition it should be fine to remove it I guess.

I think for next major it will be removed and replaced by something else, I already have an idea.

**Comment by HuskyDG** [comment]
You can pin this issues to notify everyone

**Comment by Fox2Code** [comment]
Magisk-Module-Repo is dead.
