### ISSUE TITLE
Change module download location

### ISSUE THREAD

**Issue by InnerCato** [Fox2Code/FoxMagiskModuleManager#77]
Can you add an option to change the module download location like in Magisk?

**Comment by Fox2Code** [comment]
My app open your web browser to download.

As such it doesn't choose download location.

This is mainly done so I don't have to ask extra perms for storage, I really don't like asking for perms in an app unless necessary.

Please change you browser settings to ask every time.

**Comment by Fox2Code** [comment]
Also I could make download managed by the app in the future instead of using the external web browser so I will keep this an an enhancement request.

**Comment by InnerCato** [comment]
Ok

**Comment by Fox2Code** [comment]
Is this a duplicate of #60?
