### ISSUE TITLE
Getting rid of Magisk-Modules-Repo, will use `updateJson` based repo instead.

### ISSUE THREAD

**Issue by Fox2Code** [Fox2Code/FoxMagiskModuleManager#79]
I will be getting rid of Magisk-Modules-Repo in next version due to deprecated modules.

I will switch to a `updateJson` based repo.

Modules on this list will be available for download unless ask not to be added:
https://github.com/search?q=org%3AMagisk-Modules-Repo+updateJson&type=code

Off course some exceptions might be made for some modules on a whitelist basis for some popular modules.

Please post your modules `updateJson` links here if you want them to be added or removed.

**Comment by nift4** [comment]
https://github.com/nift4/microg_installer_revived

**Comment by Fox2Code** [comment]
Well I found out all modules have either switched to Magisk-Module-Alt-Repo or Androidacy-Repo.

**Comment by Fox2Code** [comment]
I think I can close this since most module migrated.
