### ISSUE TITLE
Ability to Sort

### ISSUE THREAD

**Issue by bassmadrigal** [Fox2Code/FoxMagiskModuleManager#8]
Am I just blind and missing it? Is there a way to choose the sort method for the list of modules? Personally, I'd be interested in alphabetically, but I imagine there's other sort types that others would be interested in.

If not, would this be something that can be added?

**Comment by Fox2Code** [comment]
Yeah, it's something I want to make too, just need to balance between life and dev.
With my current health I can't work really fast on any project, but I am still working on this project anyway.

**Comment by Fox2Code** [comment]
Current implementation is:

Updatable -> Sort by last update date first
Installed -> Sort alphabetically from A to Z
Online repo -> Sort by last update date first

I think I will probably make the filter only affect the online repo section?
What do you think?
Or would you prefer some alternate implementation?

**Comment by bassmadrigal** [comment]
Installed remaining alphabetical and then being able to choose between last updated or alphabetical for the online repo would be my ideal preference.

No rush on things. I just wanted to make sure I wasn't missing an option that already existed. Thanks for your work on this app!

**Comment by Fox2Code** [comment]
WIP, high chances to be implemented in `0.3.0`!
(There will be a `0.2.7` before a `0.3.0` tho)

**Comment by Fox2Code** [comment]
Implemented in [`3.0.0-dev1`](https://github.com/Fox2Code/FoxMagiskModuleManager/releases/tag/3.0.0-dev1)

Feel free to open a new issue if the dev build have a bug with this feature.
