### ISSUE TITLE
Request: language selection

### ISSUE THREAD

**Issue by nezorflame** [Fox2Code/FoxMagiskModuleManager#80]
As a user I would like to see a language selection option so that I could e.g. pick English despite my device language.

**Comment by Fox2Code** [comment]
Wait for someone to do it for me because I can't (See #71)

**Comment by nezorflame** [comment]
Got it!
Maybe let's leave this open with "help wanted" tag so that people might see this in the future?

**Comment by Madis0** [comment]
While I am not sure about Android 12 and below, this is the tutorial for Android 13's feature: https://developer.android.com/about/versions/13/features/app-languages

**Comment by Fox2Code** [comment]
Implemented by @DerGoogler, development built should come soon!

**Comment by Fox2Code** [comment]
I forgot to close, it's implemented in development builds!
