### ISSUE TITLE
[BUG] Lawnchair not visible on online repo

### ISSUE THREAD

**Issue by d3radicated** [Fox2Code/FoxMagiskModuleManager#87]
**Describe the bug**
I tried to search for Lawnchair on the app but it's not showing up. I checked the [modules repo](https://github.com/Magisk-Modules-Alt-Repo/json/blob/c53342cb38bc4b86a901a1be92ddcfefad2f2093/modules.json#L252-L259) and it is there.

**To Reproduce**
1. Search for "Lawnchair"
2. Only QuickSwitch module is listed

**Expected behavior**
Lawnchair should be displayed as a search result

**Device info(please complete the following information):**
 - Device: Redmi Note 8 Pro
 - OS: Pixel Experience 12
 - App Version: 0.3.2

**Comment by Fox2Code** [comment]
Hi, thank for reporting this.

The module was filtered by the "low quality module filter".

The filter is very generous to avoid false positives, and I can say in fact it wasn't a false positive.
The module author disregarded the most basic safety steps to protect users.

You can read more about it [here](https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/DEVELOPERS.md).
Also the switch to disable the "low quality module filter" is hidden behind `dev-mode`.

Any developers that understand java should be able to enable `dev-mode` or get around this filter very easily.

**Comment by Fox2Code** [comment]
You can also download the module form the author page and install it from storage tho.
Sorry that a module you like was filtered like this.
