### ISSUE TITLE
[0.4.0 RC1] Not detecting root on A11 Magisk 24

### ISSUE THREAD

**Issue by YSpoof** [Fox2Code/FoxMagiskModuleManager#98]
On 0.3.2 it was working fine, after I updated, root is "lost" on the app, app is not on DenyList, I've tried removing and giving root access again trough Magisk, and also clearing data.

(Btw, when I open Fox Mmm, I get a toast saying "Fox Mmm was granted root access")

**Comment by Fox2Code** [comment]
Weird, I tried to patch this issue because peoples were complaining about it.
I don't have the bug on any of my devices so it will be hard for me to fix it sadly.
I will make RC-2 have a debug build attached to it to let users have a full `logcat` with full information.

**Comment by YSpoof** [comment]
Okay, hope I can help

**Comment by jacko9000** [comment]
Works for me in Android 11.  I didn't need to install the debug build.  I was also having the no root or Magisk detection issue with the previous version 0.4.0-rc1.  So, the issue appears to have been resolved, at least in my case.  Hopefully, the OP will find the same result.

Thanks for the fix.

Regards,
Jacko

**Comment by YSpoof** [comment]
> Works for me in Android 11. I didn't need to install the debug build. I was also having the no root or Magisk detection issue with the previous version 0.4.0-rc1. So, the issue appears to have been resolved, at least in my case. Hopefully, the OP will find the same result.
> 
> Thanks for the fix.
> 
> Regards, Jacko

I'll say the same, no error message about root, didn't test modules install nor uninstall atm
